

INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (1, 20);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (1,'F00,1);


INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (2, 38);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (2,'F02',2);


INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (3, 25);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (3,'F03',3);

INSERT INTO BUILDING (ID) VALUES (1);

INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (1, 1);
INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (1, 2);
INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (1, 3);

INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (4, 29);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (4,'F04',4);

INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (5, 40);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (5,'F05',5);

INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (6, 10);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (6,'F06',6);

INSERT INTO BUILDING (ID, NAME) VALUES (2);

INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (2, 4);
INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (2, 5);
INSERT INTO BUILDING_ROOMS (BUILDING_ID, ROOMS_ID) VALUES (2, 6);


INSERT INTO TEMPERATURE (ID, DEGREE) VALUES (1, 20);
INSERT INTO ROOM (ID,NAME,TEMPERATURE_ID) VALUES (1,'F00,1);